### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by johncena818** [Rocail/Pocket-Rogues-Save-Editor#1]
Thanks for taking the time to make this save editor.

For some reason it crashes for me once I try to load my save file, and I am not sure what is wrong. If you could fix the crash issue that would be amazing!

Edit: using windows, the save editor may have stopped working once the game was updated to 1.36

**Comment by Rocail** [comment]
Yep, I should update the data model, 1.36 introduced a rework of the pets that changed the save file structure

**Comment by Rocail** [comment]
Fixed, check [1.0.1 release](https://github.com/Rocail/Pocket-Rogues-Save-Editor/releases/tag/1.0.1)
